---
site_name: Reusable Workflows
site_description: Reusable GitHub Actions workflows for infinite-automations
repo_url: https://github.com/infinite-automations/workflows
repo_name: infinite-automations/workflows

theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - navigation.expand
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - tables
